image:
  name: wsl2-rootfs-debian
  version: "13.0"

target:
  os: debian
  dist: debian13
  arch: x86_64
  imageType: wsl2

disk:
  name: WSL2_Rootfs
  artifacts:
    - type: tar
      compression: gz

systemConfig:
  name: WSL2_Rootfs
  packages:
    - apt
    - base-files
    - bash
    - init
    - iproute2
    - less
    - locales
    - openssh-server
    - procps
    - sudo
    - systemd
    - systemd-resolved
    - systemd-timesyncd

  additionalFiles:
    - local: ../../../../../general/wsl2/ict-wsl2-profile.sh
      final: /etc/profile.d/00-ict-wsl2.sh
    - local: ../../../../../general/wsl2/resize-filesystem.txt
      final: /usr/share/doc/ict-wsl2/resize-filesystem.txt
