name: gitleaks
on: [pull_request, push, workflow_dispatch]

permissions:
  contents: read
  pull-requests: read
  security-events: write
  actions: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          persist-credentials: true
      - name: Run Gitleaks scan
        uses: ./.github/actions/security/gitleaks
        with:
          scan-scope: "all"
          source: "./"
          config_path: "./ci/gitleaks_baselines/image-composer-tool-gitleaks.sarif"
          report_format: "sarif"
          redact: "true"